### ISSUE TITLE
Advanced Typography Field

### ISSUE THREAD

**Issue by OmarAtta** [Codestar/codestar-framework#172]
Hi :+1: 
I have created this field to improve the original typography field by adding these features as preview, line height, font size, font color and font family

![typo](https://cloud.githubusercontent.com/assets/2773235/11483550/9a0462ce-97b1-11e5-90e5-ef25cc55710a.jpg)

```php
<?php if ( ! defined( 'ABSPATH' ) ) { die; } // Cannot access pages directly.
/**
 *
 * Field: Typography Advanced
 *
 * @since 1.0.0
 * @version 1.0.0
 *
 */
class CSFramework_Option_typography_advanced extends CSFramework_Options {

  public function __construct( $field, $value = '', $unique = '' ) {
    parent::__construct( $field, $value, $unique );
  }

  public function output() {

    echo $this->element_before();

    $defaults_value = array(
      'family'       => 'Arial',
      'variant'      => 'regular',
      'font'         => 'websafe',
      'size'         => '14',
      'height'       => '',
      'color'        => '',
    );

    $default_variants = apply_filters( 'cs_websafe_fonts_variants', array(
      'regular',
      'italic',
      '700',
      '700italic',
      'inherit'
    ));

    $websafe_fonts = apply_filters( 'cs_websafe_fonts', array(
      'Arial',
      'Arial Black',
      'Comic Sans MS',
      'Impact',
      'Lucida Sans Unicode',
      'Tahoma',
      'Trebuchet MS',
      'Verdana',
      'Courier New',
      'Lucida Console',
      'Georgia, serif',
      'Palatino Linotype',
      'Times New Roman'
    ));

    $value         = wp_parse_args( $this->element_value(), $defaults_value );
    $family_value  = $value['family'];
    $variant_value = $value['variant'];
    $is_variant    = ( isset( $this->field['variant'] ) && $this->field['variant'] === false ) ? false : true;
    $is_chosen     = ( isset( $this->field['chosen'] ) && $this->field['chosen'] === false ) ? '' : 'chosen ';
    $google_json   = cs_get_google_fonts();
    $chosen_rtl    = ( is_rtl() && ! empty( $is_chosen ) ) ? 'chosen-rtl ' : '';


    //Container
    echo '<div class="cs_font_field" data-id="'.$this->field['id'].'">';


    if( is_object( $google_json ) ) {

      $googlefonts = array();

      foreach ( $google_json->items as $key => $font ) {
        $googlefonts[$font->family] = $font->variants;
      }

      $is_google = ( array_key_exists( $family_value, $googlefonts ) ) ? true : false;

      echo '<label class="cs-typography-family">';
      echo '<select name="'. $this->element_name( '[family]' ) .'" class="'. $is_chosen . $chosen_rtl .'cs-typo-family" data-atts="family"'. $this->element_attributes() .'>';

      do_action( 'cs_typography_family', $family_value, $this );

      echo '<optgroup label="'. __( 'Web Safe Fonts', 'cs-framework' ) .'">';
      foreach ( $websafe_fonts as $websafe_value ) {
        echo '<option value="'. $websafe_value .'" data-variants="'. implode( '|', $default_variants ) .'" data-type="websafe"'. selected( $websafe_value, $family_value, true ) .'>'. $websafe_value .'</option>';
      }
      echo '</optgroup>';

      echo '<optgroup label="'. __( 'Google Fonts', 'cs-framework' ) .'">';
      foreach ( $googlefonts as $google_key => $google_value ) {
        echo '<option value="'. $google_key .'" data-variants="'. implode( '|', $google_value ) .'" data-type="google"'. selected( $google_key, $family_value, true ) .'>'. $google_key .'</option>';
      }
      echo '</optgroup>';

      echo '</select>';
      echo '</label>';

      if( ! empty( $is_variant ) ) {

        $variants = ( $is_google ) ? $googlefonts[$family_value] : $default_variants;
        $variants = ( $value['font'] === 'google' || $value['font'] === 'websafe' ) ? $variants : array( 'regular' );

        echo '<label class="cs-typography-variant">';
        echo '<select name="'. $this->element_name( '[variant]' ) .'" class="'. $is_chosen . $chosen_rtl .'cs-typo-variant" data-atts="variant">';
        foreach ( $variants as $variant ) {
          echo '<option value="'. $variant .'"'. $this->checked( $variant_value, $variant, 'selected' ) .'>'. $variant .'</option>';
        }
        echo '</select>';
        echo '</label>';

      }

      echo cs_add_element( array(
        'pseudo'          => true,
        'type'            => 'number',
        'name'            => $this->element_name( '[size]' ),
        'value'           => $this->value['size'],
        'default'         => ( isset( $this->field['default']['size'] ) ) ? $this->field['default']['size'] : '',
        'wrap_class'      => 'small-input',
        'before'          => 'Font Size ',
      ) );

      echo '<div class="cs-divider"></div>';

      echo cs_add_element( array(
        'pseudo'          => true,
        'type'            => 'number',
        'name'            => $this->element_name( '[height]' ),
        'value'           => $this->value['height'],
        'default'         => ( isset( $this->field['default']['height'] ) ) ? $this->field['default']['height'] : '',
        'wrap_class'      => 'small-input',
        'before'          => 'Line Height ',
      ) );
      //echo '<div class="cs-divider"></div>';
      echo '<label class="cs-typography-color"> Color ';
      echo cs_add_element( array(
        'pseudo'          => true,
        'id'              => $this->field['id'].'_color',
        'type'            => 'color_picker',
        'name'            => $this->element_name('[color]'),
        'attributes'      => array(
          'data-atts'     => 'bgcolor',
        ),
        'value'           => $this->value['color'],
        'default'         => ( isset( $this->field['default']['color'] ) ) ? $this->field['default']['color'] : '',
        'rgba'            => ( isset( $this->field['rgba'] ) && $this->field['rgba'] === false ) ? false : '',
      ) );
      echo '</label>';

      /**
       * Font Preview
       */
      if (isset( $this->field['preview'] ) && $this->field['preview'] == true) {
        if (isset( $this->field['preview_text'] )) {
          $preview_text = $this->field['preview_text'];
        }else {
          $preview_text = 'Lorem ipsum dolor sit amet, pro ad sanctus admodum, vim at insolens appellantur. Eum veri adipiscing an, probo nonumy an vis.';
        }
        echo '<div id="preview-'.$this->field['id'].'" style="font-family:;" class="cs-font-preview">'. $preview_text .'</div>';
      }

      echo '<input type="text" name="'. $this->element_name( '[font]' ) .'" class="cs-typo-font hidden" data-atts="font" value="'. $value['font'] .'" />';

    } else {

      echo __( 'Error! Can not load json file.', 'cs-framework' );

    }

    //end container
    echo '</div>';

    echo $this->element_after();

  }

}

```

jQuery Code to Live Preview
This code is working well but it's need to improvements and I hope help me to improve it and make it simpler and clean as possible

```javascript
jQuery(document).ready(function(){
		jQuery('.cs_font_field').each(function() {
			var parentName = jQuery(this).attr('data-id');
			var currentVal = jQuery(this).find('.cs-typo-family').val();
			jQuery(this).find("#preview-"+ parentName +"").css("font-family", currentVal);
			jQuery('head').append('<link href="http://fonts.googleapis.com/css?family=' + currentVal +'" class="cs-font-preview-'+ parentName +'" rel="stylesheet" type="text/css" />').load();
			
			jQuery(this).find('.cs-typo-family').change(function(){
				jQuery('head').find(".cs-font-preview-"+ parentName +"").remove();
				var font = jQuery(this).val();
				jQuery(this).parent().parent().find("#preview-"+ parentName +"").css("font-family", font);
				jQuery('head').append('<link href="http://fonts.googleapis.com/css?family=' + font +'" class="cs-font-preview-'+ parentName +'" rel="stylesheet" type="text/css" />').load();
			});
		});
	});
```

Some css codes to style
```css
.cs-field-typography_advanced .chosen-container-single .chosen-single {
	background: #fff;
	padding: 0 5px;
	height: 28px;
	border: 1px solid #ddd;
	border-radius: 0;
	-webkit-box-shadow: inset 0 1px 2px rgba(0,0,0,.07);
	box-shadow: inset 0 1px 2px rgba(0,0,0,.07);
}
.cs-field-typography select,
.cs-field-typography .chosen-container,
.cs-field-typography_advanced select,
.cs-field-typography_advanced .chosen-container{
  margin-right: 5px;
}
.cs-field-typography .cs-typo-variant {
  min-width: 90px;
}
.cs-field-typography_advanced input[type="text"] {
	vertical-align: middle;
}
.cs-field-typography_advanced .small-input input[type="text"]{
	width: 50px;
	text-align: center;
}
.cs-divider {
	width:100%;
	display: block;
	height: 10px;
}
.cs-font-preview {
	padding: 10px;
	border: 1px solid #e6e6e6;
	color: #7b7b7b;
	margin-top: 20px;
	background-color: #fff;
	font-size: 16px;
}
.cs-field-typography_advanced .cs-field-color_picker {
  position: relative;
  top: 10px;
}
```

because we change the field class the variants will not change before saving when change the font family to fix this add this code in cs-framework.js

```javascript
$('.cs-field-typography_advanced', this).CSFRAMEWORK_TYPOGRAPHY();
```

Example of use field

```php
array(
        'id'        => 'content_font',
        'type'      => 'typography_advanced',
        'title'     => __('Typography Advanced', ''),
        'default'   => array(
          'family'  => 'Indie Flower',
          'variant' => 'regular',
          'font'    => 'google',
          'size'    => '20',
          'height'  => '18',
          'color'   => '#e2e2e2'
        ),
        'preview'   => true, //Enable or disable preview box
        //'preview_text' => 'hello world', //Replace preview text with any text you like.
      ),
```

I'm sorry for my bad English :-1:

**Comment by Codestar** [comment]
Hi,

Oh yes nice. my english same :smile: hmm ok i noted this for next framework updates. I liked it :+1: Some users need this Advanced typography options yes. Good.

Thanks for contribute.
Regards, Codestar

**Comment by OmarAtta** [comment]
Some CSS improvements
![css-improvments](https://cloud.githubusercontent.com/assets/2773235/11571919/69d3f274-9a07-11e5-9488-cee2b7e25359.jpg)

Use icons instead of texts

Add this code to style file

```css
.cs-field-typography_advanced .cs-field-number:before {
	content: "\f034";
	position: absolute;
	top: 2px;
	left : 2px;
	height: 25px;
	width: 25px;
	font-family: 'FontAwesome';
	line-height: 2;
	text-align:center;
	background-color: #ededed;
	display: block;
}
.cs-field-typography_advanced .cs-field-number.cs-font-height:before {
	content: "\f07d";
}
```

wrap class for font size is 'cs-font-size' and for line height 'cs-font-height' and for best user experience add title attribute to field as :

```php
'attributes'    => array(
        'title'   => __('Line Height', 'cs-framework'),
),
```

BTW, thanks for this amazing framework :100:
