### ISSUE TITLE
Feature Request: Horizontal Layout for Multiple Color Pickers

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#245]
Feature Request: Horizontal Layout for Multiple Color Pickers

**Comment by Codestar** [comment]
You can do this with ```Fieldset``` field with a little custom css. for eg:

```php
// add fieldset config array attribute
'wrap_class' => 'fieldset-horizontal'
```

```css
// add custom css on your admin panel
.fieldset-horizontal .cs-element {
  display: inline-block;
  padding: 0;
  margin-right: 5px;
  border: none;
}
.fieldset-horizontal .cs-element .cs-title {
  width: 100%;
  float: none;
  margin-bottom: 5px;
}
.fieldset-horizontal .cs-element .cs-fieldset {
  margin: 0;
}
.fieldset-horizontal .cs-inner {
  border: none;
  background-color: transparent;
}
```

See the output:
![support_12-39-07](https://cloud.githubusercontent.com/assets/1313301/13916223/024ecec0-ef62-11e5-86d4-4526d3dbaf40.png)
