### ISSUE TITLE
Add new field ui_slider

### ISSUE THREAD

**Issue by kenthd** [Codestar/codestar-framework#313]
Hi,

This framework is great, but currently I see is lack of type slider, you can review and add new fields to? :+1:  

https://jqueryui.com/slider/

Thanks and best regards,
KENT

**Comment by Codevz** [comment]
I'm using this: 

<img src="http://i.imgur.com/2lbges6.png" />

Slider field

```PHP
<?php if ( ! defined( 'ABSPATH' ) ) { die; } // Cannot access pages directly.
/**
 *
 * Field: Slider
 *
 * @since 1.0.0
 * @version 1.0.0
 *
 */
class CSFramework_Option_slider extends CSFramework_Options {

  public function __construct( $field, $value = '', $unique = '' ) {
    parent::__construct( $field, $value, $unique );
  }

  public function output() {

	$rand = rand( 1, 9999 );
	$options = array(
		'unit' 	=> ( empty( $this->field['options']['unit'] ) ) ? 'px' : $this->field['options']['unit'],
		'min' 	=> ( empty( $this->field['options']['min'] ) ) ? '1' : $this->field['options']['min'],
		'max' 	=> ( empty( $this->field['options']['max'] ) ) ? '200' : $this->field['options']['max']
	);

	echo $this->element_before();
	echo '<div class="cs-slider"><div></div></div>';
	echo '<input data-slider=\'' . json_encode( $options ) . '\' type="'. $this->element_type() .'" name="'. $this->element_name() .'" value="'. $this->element_value() .'"'. $this->element_class() . $this->element_attributes() .'/>';
	echo $this->element_after();

  }

}
```

jQuery
```javascript
$( '.cs-field-slider' ).each(function() { 
	var dis 	= $( this ),
		input 	= $( 'input', dis ),
		slider 	= $( '.cs-slider > div', dis ),
		data 	= input.data( 'slider' );

	slider.slider({
		range: "min",
		value: parseInt( input.val() ) || 0,
		min: parseInt( data.min ) || 0,
		max: parseInt( data.max ) || 200,
		slide: function( event, ui ) {
			input.val( ui.value + data.unit ).trigger( 'change' );
		}
	});

	input.keyup(function() {
		slider.slider( "value" , ( parseInt( input.val() ) || 0 ) );
	});

});
```

CSS
```css
.cs-field-slider input {
    display: inline-block;
    width: 27%;
}
.cs-slider {
    display: inline-block;
    margin: 0 8% 0 0;
    width: 64%;
    vertical-align: super;
}
.cs-field-slider .ui-slider {
    position: relative;
    width: 100%;
    height: 2px;
    background: #E8E8E8;
}
.cs-field-slider .ui-slider-range {
    background: #111;
    height: 2px;
}
.cs-field-slider .ui-slider-handle {
    height: 10px;
    width: 10px;
    background: #111;
    position: absolute;
    top: -4px;
    border-radius: 100%;
}
```

Usage
```PHP
array(
	'id'        => 'font-size',
	'type'      => 'slider',
	'title'     => __( 'Font size', 'codevz' ),
	'options'   => array(
		'min' 	  => 1,
		'max' 	  => 132,
		'unit' 	  => 'px'
	)
)
```
