### ISSUE TITLE
Shortcode UI in WooCommerce Product Page Issue

### ISSUE THREAD

**Issue by pn1gh2** [Codestar/codestar-framework#411]
"Shortcode" popup stays behind text editor when on WooCommerce product page. I took screenshot to show you. Also, there are two (x) icons to close "Shortcode" popup UI.

I think it might be css issue (probably z-index) or script? from Codestar framework core file. That - I dare not to touch.

![hw7y3lw](https://cloud.githubusercontent.com/assets/13285056/18695076/3d268938-7f7d-11e6-9a88-909990d03314.png)

**Comment by Codestar** [comment]
Hmm, Woocommerce affect jquery ui dialog... you can add this custom css for your admin panel.

```css
.ui-widget-overlay {
    z-index: 9999 !important;
}

.ui-dialog {
    z-index: 99999 !important;
}
````
