### ISSUE TITLE
Radio Group Field

### ISSUE THREAD

**Issue by OmarAtta** [Codestar/codestar-framework#435]
Hi,
I've created this field to replace default OS style with custom CSS

screenshot
![radio-group](https://cloud.githubusercontent.com/assets/2773235/21733387/df38a524-d466-11e6-87d6-c1affb4d08ea.gif)

1. Field code
Create new field with name "radio_group" and paste this code inside it

```php
<?php if ( ! defined( 'ABSPATH' ) ) { die; } // Cannot access pages directly.
/**
 *
 * Field: Radio
 *
 * @since 1.0.0
 * @version 1.0.0
 *
 */
class CSFramework_Option_radio_group extends CSFramework_Options {
  public function __construct( $field, $value = '', $unique = '' ) {
    parent::__construct( $field, $value, $unique );
  }
  public function output(){
    echo $this->element_before();
    if( isset( $this->field['options'] ) ) {
      $options = $this->field['options'];
      $options = ( is_array( $options ) ) ? $options : array_filter( $this->element_data( $options ) );
      if( ! empty( $options ) ) {
        echo '<ul'. $this->element_class('dt-radio-group') .'>'; // << replace this class <<
        foreach ( $options as $key => $value ) {
          echo '<li>';
          echo '<input type="radio" id="field_'.$this->field['id'].'_'.$key.'" name="'. $this->element_name() .'" value="'. $key .'"'. $this->element_attributes( $key ) . $this->checked( $this->element_value(), $key ) .'/>';
          echo '<label for="field_'.$this->field['id'].'_'.$key.'">'. $value .'</label>';
          echo '</li>';
        }
        echo '</ul>';
      }
    } else {
      $label = ( isset( $this->field['label'] ) ) ? $this->field['label'] : '';
      echo '<label><input type="radio" name="'. $this->element_name() .'" value="1"'. $this->element_class() . $this->element_attributes() . checked( $this->element_value(), 1, false ) .'/> '. $label .'</label>';
    }
    echo $this->element_after();
  }
}

```

2. Style file
Inside your css file paste this code

```css
.dt-radio-group {
  font-size: 0;
}
.dt-radio-group li {
  display: inline-block;
  font-size: 14px;
}
.dt-radio-group input[type="radio"]{
  display: none; /* Hide radio button to use label insted */
}
.dt-radio-group label {
  display: inline-block;
  padding: 0 15px !important;
  background: #60646D; /* Change this to change background color */
  color: #999; /* Change this to change text color */
  height: 35px;
  line-height: 35px; /* Use this to vertical center text */
  cursor: pointer;
  font-size: 14px;
  transition: all 0.2s linear;
}
.dt-radio-group input[type="radio"]:checked + label {
      background: #1DABB8;
      color: #fff;
}
.dt-radio-group li:first-child label {
  border-radius: 5px 0 0 5px; /* top left, top right, bottom right, bottom left */
}
.dt-radio-group li:last-child label {
  border-radius: 0 5px 5px 0; /* top left, top right, bottom right, bottom left */
}
```

You can change "dt-radio-group" class to whatever you want by replace `$this->element_class('dt-radio-group')`

2. Use field
```php
array(
  'id'              => 'radio_group_test',
  'type'            => 'radio_group',
   'title'           => __('Radio Group Field Sample', 'yourtextdomain'),
   'options' => array(
      'enable'     => 'Enable',
      'default'    => 'Default',
      'disable'    => 'Disable',
    ),
    'default' => 'default',
),
```
