### ISSUE TITLE
How to customize the height of Code Editor

### ISSUE THREAD

**Issue by scmyyc** [Codestar/codestar-framework#46]
How to customize the height of Code Editor？

**Comment by Codestar** [comment]
Add this on your custom admin.css:

```css
.my-code-editor .CodeMirror,
.my-code-editor textarea{
  height: 400px;
}
```
then add class parameter:
```php
array(
  'id'    => 'my_code_editor',
  'type'  => 'code_editor',
  'class' => 'my-code-editor',
),
```
